# Generated by Django 3.2.9 on 2021-11-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerakiDataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('org_id', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=64)),
                ('sensor', models.CharField(choices=[('TM', 'Temperature'), ('HD', 'Humidity'), ('OC', 'Occupancy')], max_length=2)),
                ('interval', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('TM', 'Temperature'), ('HD', 'Humidity'), ('OC', 'Occupancy')], max_length=2)),
                ('tstamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('ds_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardApp.merakidatasource')),
            ],
        ),
    ]
